"""Deterministic reproducible-code exporters for figure versions.

Generates plain text only: a self-contained Python/matplotlib script and a
LaTeX inclusion snippet. Nothing here imports matplotlib/plotnine (they are
not installed server-side); the user runs the emitted code locally.

Every user-controlled value (figure name, dataset name, column names, labels)
is embedded through ``json.dumps``/character escaping so the emitted code is
always syntactically valid and cannot be broken out of by hostile strings.
"""
from __future__ import annotations

import json
import re
from typing import Any

# ------------------------------------------------------------- small helpers

def _s(text: Any) -> str:
    """A safe Python string literal for user-controlled text (double-quoted,
    ASCII-escaped by json.dumps, so it can never terminate the literal)."""
    return json.dumps(str(text))


def _col(name: str) -> str:
    """A df[...] accessor with the column name safely quoted."""
    return f"df[{_s(name)}]"


def _num(value: Any) -> float | None:
    try:
        out = float(value)
    except (TypeError, ValueError):
        return None
    if out != out or out in (float("inf"), float("-inf")):  # NaN / inf guard
        return None
    return out


def _flag(options: dict, key: str) -> bool:
    return bool(options.get(key))


def _mapped_column(mapping: dict, key: str, valid_columns: set[str]) -> str | None:
    """A mapping entry, kept only when it is a plausible column reference."""
    value = mapping.get(key)
    if not isinstance(value, str) or not value.strip():
        return None
    value = value.strip()
    if valid_columns and value not in valid_columns:
        return None
    return value


def _mapped_columns(mapping: dict, key: str, valid_columns: set[str]) -> list[str]:
    value = mapping.get(key)
    if isinstance(value, str):
        value = [value]
    if not isinstance(value, list):
        return []
    out: list[str] = []
    for item in value:
        if isinstance(item, str) and item.strip():
            item = item.strip()
            if not valid_columns or item in valid_columns:
                out.append(item)
    return out


_HEATMAP_CMAPS = {
    "blue_red": "RdBu_r",
    "viridis": "viridis",
    "magma": "magma",
    "inferno": "inferno",
    "plasma": "plasma",
    "cividis": "cividis",
}


# ------------------------------------------------------ python (matplotlib)

def generate_python_code(
    figure_name: str,
    dataset_name: str,
    column_names: set[str] | None,
    plot_type: str,
    mapping: dict | None,
    options: dict | None,
    output_basename: str = "figure",
) -> str:
    mapping = mapping if isinstance(mapping, dict) else {}
    options = options if isinstance(options, dict) else {}
    valid = set(column_names or set())

    body, needs_numpy = _python_plot_body(plot_type, mapping, options, valid)

    lines: list[str] = [
        "# Generated by LabPlot AI - reproducible matplotlib export",
        f"# Figure: {_comment_safe(figure_name)}",
        "# Date: <date of export>",
        "#",
        "# This script reproduces the figure locally. It requires:",
        "#   pip install pandas matplotlib" + (" numpy" if needs_numpy else ""),
        "",
        "import pandas as pd",
        "import matplotlib.pyplot as plt",
    ]
    if needs_numpy:
        lines.append("import numpy as np")
    lines += [
        "",
        f"df = pd.read_csv({_s(str(dataset_name) + '.csv')})  # export your dataset from LabPlot first",
        "",
        _figure_open_line(options),
    ]
    lines += body
    lines += _python_decorations(plot_type, mapping, options, valid)
    dpi = _num(options.get("dpi"))
    save_dpi = int(dpi) if dpi and dpi > 0 else 300
    lines += [
        "",
        "plt.tight_layout()",
        f"plt.savefig({_s(output_basename + '.png')}, dpi={save_dpi})",
        f"plt.savefig({_s(output_basename + '.pdf')})",
        "plt.show()",
        "",
        "# Tip: paste into a Jupyter cell, or save as figure.qmd code chunk for Quarto.",
        "",
    ]
    return "\n".join(lines)


def _comment_safe(text: Any) -> str:
    """Text safe to embed on a single comment line (no newlines)."""
    return re.sub(r"[\r\n]+", " ", str(text)).strip()


def _figure_open_line(options: dict) -> str:
    width = _num(options.get("width_in"))
    height = _num(options.get("height_in"))
    if width and height and width > 0 and height > 0:
        return f"plt.figure(figsize=({round(width, 3)}, {round(height, 3)}))"
    return "plt.figure(figsize=(7.0, 4.8))"


def _alpha(options: dict, key: str, default: float) -> float:
    value = _num(options.get(key))
    if value is None:
        return default
    return min(max(value, 0.0), 1.0)


def _group_loop(plot_call_template: str, group: str, legend_title: str | None = None) -> list[str]:
    """Manual groupby loop with a tab10 colour cycle (no seaborn needed).

    ``plot_call_template`` must contain '{color}' where the colour goes and use
    ``sub`` as the per-group dataframe.
    """
    return [
        'cmap = plt.get_cmap("tab10")',
        f"for i, (level, sub) in enumerate(df.groupby({_s(group)})):",
        "    " + plot_call_template.format(color="cmap(i % 10)"),
        f"plt.legend(title={_s(legend_title or group)})",
    ]


def _python_plot_body(plot_type: str, mapping: dict, options: dict,
                      valid: set[str]) -> tuple[list[str], bool]:
    """Plot-type specific body lines. Returns (lines, needs_numpy)."""
    x = _mapped_column(mapping, "x", valid)
    y = _mapped_column(mapping, "y", valid)
    group = _mapped_column(mapping, "group", valid) or _mapped_column(mapping, "color", valid)

    if plot_type == "scatter" and x and y:
        return _scatter_body(x, y, group, options)
    if plot_type == "line" and x and y:
        return _line_body(x, y, group, options)
    if plot_type == "bar" and x:
        return _bar_body(x, y, options)
    if plot_type == "box" and x and y:
        return _box_body(x, y, violin=False)
    if plot_type == "violin" and x and y:
        return _box_body(x, y, violin=True)
    if plot_type == "histogram":
        value = _mapped_column(mapping, "value", valid)
        if value:
            return _histogram_body(value, group, options)
    if plot_type == "heatmap":
        columns = _mapped_columns(mapping, "columns", valid)
        if columns:
            row_label = _mapped_column(mapping, "row_label", valid)
            return _heatmap_body(columns, row_label, options)
    return _fallback_body(plot_type, x, y, options)


def _scatter_body(x: str, y: str, group: str | None, options: dict) -> tuple[list[str], bool]:
    alpha = _alpha(options, "point_alpha", 0.8)
    lines: list[str] = []
    if group:
        lines += _group_loop(
            f"plt.scatter(sub[{_s(x)}], sub[{_s(y)}], label=str(level), color={{color}}, alpha={alpha}, s=24)",
            group,
        )
    else:
        lines.append(f"plt.scatter({_col(x)}, {_col(y)}, alpha={alpha}, s=24)")
    needs_numpy = False
    if _flag(options, "add_smooth"):
        needs_numpy = True
        lines += [
            "",
            "# Linear trend line (matplotlib has no geom_smooth; simple least squares)",
            f"xy = df[[{_s(x)}, {_s(y)}]].dropna()",
            f"coef = np.polyfit(xy[{_s(x)}], xy[{_s(y)}], 1)",
            f"xs = np.linspace(xy[{_s(x)}].min(), xy[{_s(x)}].max(), 100)",
            'plt.plot(xs, coef[0] * xs + coef[1], color="black", linewidth=1.0)',
        ]
    return lines, needs_numpy


def _line_body(x: str, y: str, group: str | None, options: dict) -> tuple[list[str], bool]:
    marker = '"o"' if options.get("point_shape") != "none" else "None"
    if group:
        lines = _group_loop(
            f"plt.plot(sub.sort_values({_s(x)})[{_s(x)}], sub.sort_values({_s(x)})[{_s(y)}], "
            f"label=str(level), color={{color}}, marker={marker})",
            group,
        )
    else:
        lines = [
            f"ordered = df.sort_values({_s(x)})",
            f"plt.plot(ordered[{_s(x)}], ordered[{_s(y)}], marker={marker})",
        ]
    return lines, False


def _bar_body(x: str, y: str | None, options: dict) -> tuple[list[str], bool]:
    stat = options.get("stat") if options.get("stat") in ("mean", "sum", "count") else "mean"
    if not y or stat == "count":
        return [
            f"counts = {_col(x)}.value_counts()",
            "plt.bar(counts.index.astype(str), counts.values)",
        ], False

    lines = [f"grouped = df.groupby({_s(x)})[{_s(y)}]"]
    agg = "sum" if stat == "sum" else "mean"
    lines.append(f"heights = grouped.{agg}()")
    needs_numpy = False
    if _flag(options, "error_bars") and stat == "mean":
        error_type = options.get("error_type") if options.get("error_type") in ("sd", "se", "ci95") else "sd"
        if error_type == "sd":
            lines.append("err = grouped.std()  # standard deviation")
        else:
            needs_numpy = True
            lines.append("err = grouped.std() / np.sqrt(grouped.count())  # standard error")
            if error_type == "ci95":
                lines.append("err = 1.96 * err  # 95% confidence interval")
        lines.append("plt.bar(heights.index.astype(str), heights.values, yerr=err.values, capsize=3)")
    else:
        lines.append("plt.bar(heights.index.astype(str), heights.values)")
    return lines, needs_numpy


def _box_body(x: str, y: str, violin: bool) -> tuple[list[str], bool]:
    lines = [
        f"levels = [str(level) for level, _ in df.groupby({_s(x)})]",
        f"groups = [sub[{_s(y)}].dropna() for _, sub in df.groupby({_s(x)})]",
    ]
    if violin:
        lines.append("plt.violinplot(groups, showmedians=True)")
    else:
        lines.append("plt.boxplot(groups)")
    lines.append("plt.xticks(range(1, len(levels) + 1), levels)")
    return lines, False


def _histogram_body(value: str, group: str | None, options: dict) -> tuple[list[str], bool]:
    bins = _num(options.get("bins"))
    bins_arg = int(bins) if bins and bins > 0 else 30
    if group:
        alpha = _alpha(options, "fill_alpha", 0.55)
        lines = _group_loop(
            f"plt.hist(sub[{_s(value)}].dropna(), bins={bins_arg}, alpha={alpha}, "
            f"label=str(level), color={{color}})",
            group,
        )
    else:
        alpha = _alpha(options, "fill_alpha", 0.9)
        lines = [f"plt.hist({_col(value)}.dropna(), bins={bins_arg}, alpha={alpha})"]
    return lines, False


def _heatmap_body(columns: list[str], row_label: str | None, options: dict) -> tuple[list[str], bool]:
    cmap = _HEATMAP_CMAPS.get(str(options.get("palette")), "RdBu_r")
    cols_literal = "[" + ", ".join(_s(c) for c in columns) + "]"
    lines = [f"value_columns = {cols_literal}"]
    if row_label:
        lines.append(f"mat = df.set_index({_s(row_label)})[value_columns]")
    else:
        lines.append("mat = df[value_columns]")
    needs_numpy = False
    if _flag(options, "scale_rows"):
        needs_numpy = True
        lines += [
            "# Z-score each row (as in the LabPlot render)",
            "values = mat.to_numpy(dtype=float)",
            "values = (values - np.nanmean(values, axis=1, keepdims=True)) / np.nanstd(values, axis=1, keepdims=True)",
        ]
        matrix_expr = "values"
    else:
        matrix_expr = "mat.to_numpy(dtype=float)"
    lines += [
        f'im = plt.imshow({matrix_expr}, aspect="auto", cmap={_s(cmap)})',
        "plt.colorbar(im)",
        "plt.xticks(range(len(value_columns)), value_columns, rotation=90)",
    ]
    if row_label:
        lines.append("plt.yticks(range(len(mat.index)), [str(v) for v in mat.index])")
    return lines, needs_numpy


def _fallback_body(plot_type: str, x: str | None, y: str | None,
                   options: dict) -> tuple[list[str], bool]:
    lines = [
        f"# Plot type {_comment_safe(plot_type)!r} has no direct matplotlib template;",
        "# see the R export for the exact recipe.",
    ]
    if x and y:
        alpha = _alpha(options, "point_alpha", 0.8)
        lines += [
            "# Basic x/y view of the mapped columns:",
            f"plt.scatter({_col(x)}, {_col(y)}, alpha={alpha}, s=24)",
        ]
    elif x:
        lines += [
            "# Basic view of the mapped x column:",
            f"plt.plot({_col(x)}.reset_index(drop=True))",
        ]
    else:
        lines += [
            "print(df.head())",
        ]
    return lines, False


def _python_decorations(plot_type: str, mapping: dict, options: dict,
                        valid: set[str]) -> list[str]:
    """Title / axis labels / scales / limits shared by all plot types."""
    lines: list[str] = [""]
    title = options.get("title")
    if isinstance(title, str) and title.strip():
        lines.append(f"plt.title({_s(title.strip())})")

    x = _mapped_column(mapping, "x", valid) or _mapped_column(mapping, "value", valid)
    y = _mapped_column(mapping, "y", valid)
    x_label = options.get("x_label")
    y_label = options.get("y_label")
    x_label = x_label.strip() if isinstance(x_label, str) and x_label.strip() else x
    if isinstance(y_label, str) and y_label.strip():
        y_label = y_label.strip()
    elif y:
        y_label = y
    elif plot_type == "histogram":
        y_label = "Count"
    else:
        y_label = None
    if x_label and plot_type != "heatmap":
        lines.append(f"plt.xlabel({_s(x_label)})")
    if y_label and plot_type != "heatmap":
        lines.append(f"plt.ylabel({_s(y_label)})")

    if _flag(options, "log_x"):
        lines.append('plt.xscale("log")')
    if _flag(options, "log_y"):
        lines.append('plt.yscale("log")')

    x_min, x_max = _num(options.get("x_min")), _num(options.get("x_max"))
    y_min, y_max = _num(options.get("y_min")), _num(options.get("y_max"))
    if x_min is not None or x_max is not None:
        lines.append(f"plt.xlim({x_min if x_min is not None else 'None'}, {x_max if x_max is not None else 'None'})")
    if y_min is not None or y_max is not None:
        lines.append(f"plt.ylim({y_min if y_min is not None else 'None'}, {y_max if y_max is not None else 'None'})")
    return lines if len(lines) > 1 else []


# ---------------------------------------------------------------- LaTeX

_LATEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
    "$": r"\$",
}


def _latex_escape(text: Any) -> str:
    """Escape LaTeX special characters (single pass, so no double-escaping)."""
    cleaned = re.sub(r"[\r\n]+", " ", str(text)).strip()
    return "".join(_LATEX_ESCAPES.get(ch, ch) for ch in cleaned)


def _slug(text: Any) -> str:
    ascii_text = str(text).encode("ascii", "ignore").decode("ascii").lower()
    slug = re.sub(r"[^a-z0-9]+", "-", ascii_text).strip("-")
    return slug or "figure"


def generate_latex_snippet(figure_name: str, caption: str | None, basename: str) -> str:
    caption_text = caption.strip() if isinstance(caption, str) and caption.strip() else str(figure_name)
    lines = [
        "% Generated by LabPlot AI - LaTeX figure inclusion snippet",
        f"% Figure: {_latex_escape(figure_name)}",
        "% Place the exported PDF next to your .tex file (or adjust the path).",
        r"\begin{figure}[htbp]",
        r"    \centering",
        f"    \\includegraphics[width=\\linewidth]{{{basename}.pdf}}",
        f"    \\caption{{{_latex_escape(caption_text)}}}",
        f"    \\label{{fig:{_slug(figure_name)}}}",
        r"\end{figure}",
        "",
    ]
    return "\n".join(lines)
